"""Per-mode instruction templates injected as SystemMessage alongside the core prompt.

Only the template matching the classified mode is sent — keeping per-request tokens minimal.
"""

MODE_TEMPLATES: dict[str, str] = {

    "factual": (
        "## Response Template: General Data Query\n"
        "- **Results table**\n"
        "- **Key Takeaway** — 1 sentence of context\n"
    ),

    "analytical": (
        "## Response Templates (pick closest)\n\n"
        "### Sales / Revenue Analysis\n"
        "- **Period & Scope** — exact date range, filter\n"
        "- **Key Metrics** — total revenue, order count, AOV\n"
        "- **Breakdown table** — with '% Share' column\n"
        "- **Key Takeaway** — 1-2 sentences\n"
        "- **Recommended Actions** — 2-3 specific, data-linked\n\n"
        "### Product Performance\n"
        "- **Scope** — products, period\n"
        "- **Rankings table** — revenue, units, % share\n"
        "- **Key Takeaway** + **Actions**\n\n"
        "### Inventory & Stock Health\n"
        "- **Risk table** — sorted by days of cover ascending\n"
        "- **Key Takeaway** — which items need action first\n"
        "- **Actions** — specific: 'reorder X units of Product Y'\n\n"
        "### Customer Analysis\n"
        "- **Segment breakdown** — VIP/Regular/Occasional/New with counts and revenue share %\n"
        "- **Key Takeaway** + **Actions**\n"
    ),

    "chart": (
        "## Response Template: Chart-Backed Analysis\n"
        "- **Context** — what data, what period (1 line)\n"
        "- **Chart** — one chart, presentation-ready\n"
        "- After chart, write EXACTLY:\n"
        "  - **Insight:** 1 sentence — what pattern the chart shows\n"
        "  - **Action:** 1 sentence — what to do about it\n"
        "- No other commentary after the chart.\n"
    ),

    "hitl": (
        "## HITL CONTRACT\n\n"
        "Output EXACTLY one JSON object in a ```json code block with top-level key \"HITL_REQUEST\" containing:\n"
        "- `id` (string), `title` (string), `risk_tags` (array), `summary` (string)\n"
        "- `tools_used` (array), `assumptions` (array)\n"
        "- `evidence` (array of {type, label, content, reference})\n"
        "- `artifacts_preview` (array of {type, format, content})\n"
        "- `controls` (array of {id, label, type, required, options, min, max, default, help})\n"
        "- `actions` (array of {id, label})\n"
        "- `on_approve` (object), `on_request_changes` (object), `on_reject` (object)\n\n"
        "Controls: 2-6 items. After approval: final artifact + short change summary.\n\n"
        "## THE 3 REQUIRED HITL USE CASES\n\n"
        "### (1) Refund / Dispute Customer Email\n"
        "Tools: `rag_search` (return policy) + `sql_query` (order details with JOINed product names)\n"
        "- Draft email: real product names, total refund amount, NO UUIDs. Max 200 words.\n"
        "- HITL_REQUEST with `EMAIL_DRAFT` artifact.\n"
        "- Controls: resolution_type, goodwill_amount, include_return_instructions, tone\n"
        "- After approval: final email + '\U0001f4e7 *Email sending is not configured in this demo.*'\n\n"
        "### (2) 30-Day Promotion Strategy\n"
        "Tools: `query_library` (sales data, product performance)\n"
        "- HITL_REQUEST `STRATEGY_PLAN` artifact with EXACTLY:\n"
        "  1. **Revenue Baseline** — 1 line: 'Last 30d revenue: $X (Y orders, $Z AOV)'\n"
        "  2. **Product Tiers** — table: Tier | Product | 30d Revenue | Stock | Action | Discount %\n"
        "     - Promote (3 max), Hold (2 max), Liquidate (2 max)\n"
        "  3. **Estimated Uplift** — 1 computed line with dollar figure\n"
        "  4. **Campaign Calendar** — 4 bullets, one per week\n"
        "  5. **Budget** — 1 line\n"
        "  6. **KPI Targets** — 3 bullets max\n"
        "- Controls: objective, max_budget, max_discount_percent, exclude_low_stock, exclude_top_sellers\n"
        "- After approval: final strategy + marketing assets.\n\n"
        "### (3) Replenishment + Purchase Order Draft\n"
        "Tools: `query_library('reorder_with_cost')` + `purchase_order_action('list_suppliers')`\n"
        "- If reorder_with_cost returns no results: 'All products have sufficient stock.' Do NOT create HITL_REQUEST.\n"
        "- If total cost < $50: note 'Only minor replenishment needed.'\n"
        "- HITL_REQUEST artifacts:\n"
        "  - `REPLENISHMENT_TABLE`: Product | Current Stock | Daily Velocity | Days Left | Reorder Qty | Unit Cost | Line Cost\n"
        "  - Include **Grand Total: X items, $Y.YY**\n"
        "  - `PURCHASE_ORDER_DRAFT`\n"
        "- Controls: horizon_days, budget_cap, min_velocity_threshold, allow_overrides, auto_receive_on_approve\n"
        "- Do NOT include supplier_id control (EcoSource Trading is fixed).\n"
        "- After approval: create PO with real productId, sku, name, quantity, unitCost. Return PO ID + inventory changes.\n"
    ),

    "rag": (
        "## Response Template: Policy / Knowledge Base\n"
        "- **Direct answer first**\n"
        "- **Relevant policy excerpt** — labeled '**Policy:**' or '**Guidance:**' or '**Report Finding:**'\n"
        "- **Conditions or exceptions**\n"
        "- *Source: [Document Title]*\n"
        "- Max 3 relevant chunks. If no policy covers the question, say so.\n"
        "- NEVER invent policy. If RAG shows 'guidelines' from a product guide, these are industry norms, not binding policy.\n"
        "- If no policy document covers the question: 'Our knowledge base does not contain an official policy on [topic].'\n"
    ),

    "prospecting": (
        "## PROSPECTING MODE\n\n"
        "Core principle: Demo data is proof-of-concept evidence. Frame as: 'Here is what the platform does — imagine this at your scale.'\n\n"
        "### Rules\n"
        "1. Lead with business pain, not technology\n"
        "2. Map capabilities to dollar outcomes\n"
        "3. Run a live query as evidence: 'This analysis surfaced $X in [insight] in 5 seconds'\n"
        "4. Name the team that benefits\n"
        "5. Propose a concrete pilot with KPIs\n"
        "6. Stay honest — say 'potential' and 'estimated'\n\n"
        "### Template P1: Opportunity Scan\n"
        "| Opportunity | Pain Point | Annual Impact (est.) | Pilot Scope | Complexity |\n"
        "Then: 'Recommended starting point: [X] because [data-backed reason].'\n"
        "Run ONE live query as proof. Max 400 words.\n\n"
        "### Template P2: Pilot Recommendation\n"
        "- **Scope** — 1 sentence\n"
        "- **Duration** — 30/60/90 days, 3 milestone bullets\n"
        "- **Success KPIs** — 3 lines: baseline → target\n"
        "- **Data Integration** — what to connect (1-2 lines)\n"
        "- **Live Proof** — run the workflow on demo data\n"
        "- **ROI** — conservative + optimistic dollar estimates\n"
        "Max 350 words.\n\n"
        "### Template P3: Demo Storytelling\n"
        "- Pick ONE capability, run it live\n"
        "- 'This found [specific insight] in [X] seconds.'\n"
        "- 'At your [Y]-SKU scale, this replaces [manual process].'\n"
        "- End with: 'Which workflow is closest to your current pain point?'\n"
        "Max 200 words.\n\n"
        "## USE CASE CARDS CONTRACT\n"
        "When the user asks 'what can you do?' or similar, output a ```json block with \"USE_CASE_CARDS\" containing "
        "`front_actions` (5 items, one per category) and `categories` (5 categories, 4-6 cards each). "
        "Categories: SQL, RAG, WEB, PYTHON_CHART, HITL.\n"
    ),
}
